codecov:
  require_ci_to_pass: yes

comment:
  layout: "diff, flags, files, tests"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%